In [4]:
import torch

x = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], 
                  [[5.0, 6.0], [7.0, 8.0]]], requires_grad=True)
y = torch.tensor([[[0.5, 1.5], [2.5, 3.5]], 
                  [[4.5, 5.5], [6.5, 7.5]]], requires_grad=True)
z = torch.tensor([[[0.1, 0.2], [0.3, 0.4]], 
                  [[0.5, 0.6], [0.7, 0.8]]], requires_grad=True)

a = x + y
b = x - z 
c = y * z 
d = x / (y + 0.1)  
e = torch.log(x + 0.1) 
f = torch.exp(z)  

g = a * b + c  
h = d * e - f  

result = g + h * (e + 0.1)
result.backward(torch.ones_like(result))

print("Gradient of x:")
print(x.grad)
print("\nGradient of y:")
print(y.grad) 
print("\nGradient of z:")
print(z.grad)


Gradient of x:
tensor([[[ 1.8667,  6.0516],
         [ 9.1799, 12.1202]],

        [[15.0050, 17.8703],
         [20.7287, 23.5852]]])

Gradient of y:
tensor([[[0.9483, 1.5120],
         [2.3817, 3.3420]],

        [[4.3343, 5.3398],
         [6.3511, 7.3649]]])

Gradient of z:
tensor([[[ -1.2159,  -3.0283],
         [ -4.6622,  -6.2541]],

        [[ -7.8510,  -9.4771],
         [-11.1485, -12.8781]]])


tensor([[[False,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]])