In [14]:
import torch

weights1 = torch.tensor([[0.1, 0.2], [0.3, 0.4]], requires_grad=True)
inputs = torch.tensor([[0.05, 0.15], [0.25, 0.35]], requires_grad=True)
weights2 = torch.tensor([[0.01, 0.02], [0.03, 0.04]], requires_grad=True)

layer1_linear = weights1.matmul(inputs.t())
layer1_output = layer1_linear
layer1_activated = torch.relu(layer1_output)

layer2_linear = layer1_activated.matmul(weights2)
layer2_sum = layer2_linear.sum(1, keepdim=True)
layer2_output = layer2_sum

layer3_linear = layer2_output * weights1
layer3_nonlinear = torch.exp(torch.clamp(layer3_linear, -10, 10))
layer3_output = layer3_nonlinear + layer2_output

logits = layer3_output.matmul(weights2.t())
probabilities = torch.sigmoid(logits)
loss = -torch.log(probabilities + 1e-10) + 0.1
loss_sum = loss.sum(0)

loss_sum.backward(torch.ones_like(loss_sum))

print("Gradient of weights1:")
print(weights1.grad)
print("\nGradient of inputs:")
print(inputs.grad) 
print("\nGradient of weights2:")
print(weights2.grad)

Gradient of weights1:
tensor([[-0.0012, -0.0019],
        [-0.0016, -0.0024]])

Gradient of inputs:
tensor([[-0.0008, -0.0011],
        [-0.0018, -0.0026]])

Gradient of weights2:
tensor([[-1.0069, -1.0082],
        [-0.9989, -1.0002]])


In [21]:
import torch

weights1 = torch.tensor([[0.1, 0.2],
                         [0.3, 0.4]], requires_grad=True)
inputs   = torch.tensor([[0.05, 0.15],
                         [0.25, 0.35]], requires_grad=True)
weights2 = torch.tensor([[0.01, 0.02],
                         [0.03, 0.04]], requires_grad=True)

layer1_linear = weights1.matmul(inputs.transpose(0,1))
layer1_activated = torch.relu(layer1_linear)

layer2_linear = layer1_activated.matmul(weights2)
layer2_sum = layer2_linear.sum(1, keepdim=True)  # Keep dimension to make it [2,1] instead of [2]
layer2_output = layer2_sum

expand_tensor = torch.tensor([[1.0, 1.0]])
layer2_output_expanded = layer2_output.matmul(expand_tensor)

layer3_linear = layer2_output_expanded * weights1
layer3_nonlinear = torch.exp(layer3_linear)
layer3_output = layer3_nonlinear + layer2_output_expanded

logits = layer3_output.matmul(weights2.transpose(0,1))

probabilities = 1.0 / (1.0 + torch.exp(-1.0 * logits))

epsilon = 1e-10
log_probs = torch.log(probabilities + epsilon)
neg_log_probs = -1.0 * log_probs + 0.1

loss_sum = neg_log_probs.sum(0).sum(0)

loss_sum.backward()

print("Gradient of weights1:")
print(weights1.grad)
print("\nGradient of inputs:")
print(inputs.grad)
print("\nGradient of weights2:")
print(weights2.grad)

Gradient of weights1:
tensor([[-0.0012, -0.0019],
        [-0.0016, -0.0024]])

Gradient of inputs:
tensor([[-0.0008, -0.0011],
        [-0.0018, -0.0026]])

Gradient of weights2:
tensor([[-1.0069, -1.0082],
        [-0.9989, -1.0002]])
